AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://mulani-lambda-bucket/462b8a0afdcbb40a08ea138f2f2d138a
      Handler: com.mulani.java_aws_lambda.LambdaRequestHandler::handleRequest
      Runtime: java11
      Description: Java function
      MemorySize: 128
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
